apiVersion: apps/v1
kind: Deployment
metadata:
  name: bank-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: bank-app
  template:
    metadata:
      labels:
        app: bank-app
    spec:
      containers:
        - name: bank-app
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          command: ["sleep", "infinity"]